development:
  adapter: postgresql
  encoding: unicode
  database: selfstarter_development
  pool: 5
  host: localhost
  username: salayhin
  password:


test:
  adapter: postgresql
  encoding: unicode
  database: selfstarter_test
  pool: 5
  host: localhost
  username: root
  password: root